### PR TITLE
implementation of ::inside wrapper pseudo element

### PR DESCRIPTION
**Pull request by reedstrm**
This implements a new pseudo-element, that allows adding a wrapping element to all the children of a given selected element. This is useful when adding  additional children (via ::before or ::after), allowing the existing set of children to be distinguished from additions.

### CODE REVIEW

**Comment by philschatz** [comment]
Is there a way/need to wrap everything except the note title? I noticed the test generates a static (defined in CSS) note title & does not use a title in the content

**Comment by reedstrm** [comment]
This comment has nothing to do with this PR, it's a Q about a recipe, I think?

**Comment by philschatz** [comment]
To restate the previous question more-generically: How can I use `::inside` to wrap every child except a specific one?

**Comment by reedstrm** [comment]
You can't. You'd wrap all the children, then move the not-wrapped child back out to the parent, perhaps. It's not a swiss-army knife

**Pull request merged**
