### PR TITLE
move install/test scripts out of travis and into scripts dir

### PR DESCRIPTION
**Pull request by philschatz**
This moves the logic for installing dependencies and running tests out of `.travis.yml` and into the following scripts:

```sh
./scripts/setup    # Install dependencies
./scripts/test     # Run pep8 validation and unit tests
```

# TODO

- [x] remove the LESS files
- [x] move `/tests/update-log-less.sh` into `/scripts`

### CODE REVIEW

**Comment by reedstrm** [comment]
Hmm, depending on what's in setup, it'd be normal to activate first thing before installing anything. I see you do that in the script (activate/deactivate) That forces use of a virtualenv, which travis prevoiously didn't use. Looks like thay broke a few things on the tests.

**Comment by philschatz** [comment]
💭  hmm, I could skip activate/deactivate if the `TRAVIS_CI` env is set. Oddly enough, virtualenv works cnx-recipes but I don't do any coveralls reporting (yet)

**Comment by reedstrm** [comment]
You make assumptions about where the virtualenv lives. I keep one in the parent that I share between all my rewrite work (sometimes changes cut across repos - cnx-epub w/ changes in cnx-archive or publish, etc., so having both in 'develop' mode in the same venv is useful.) The new cnx-deploy puts the venvs in their own directory, under /var/lib/cnx/venvs. Others use various virtualenv wrapper scripts.

**Comment by philschatz** [comment]
💭  hmm, I approached the script from the standpoint of "I am a casual user/developer interested in tinkering but have the minimal amount set up (and no globals)". It seemed like `virtualenv .` had the fewest outside requirements to get started.

Would setting an ENV (and checking for it in the scripts) allow starting up the virtualenv elsewhere?

**Comment by reedstrm** [comment]
I'd suggest testing to see if a venv is active already before setting up a new one, or activating. Need to protect the deactivate as well, probably with `if (type -t deactivate); then deactivate; fi`

**Comment by philschatz** [comment]
cool, I can do that; how can you tell if a venv is active?

**Comment by reedstrm** [comment]
The variable VIRTUAL_ENV has the path to the VENV root.

**Comment by philschatz** [comment]
Thanks! I pushed a change which only activates the virtualenv if you are not already in one. 

Also, it seemed to me that the deactivate call was unnecessary because the virtualenv is deactivated when the script completes.

**Comment by reedstrm** [comment]
Right, virtualenv is basically just a set of shell variables (including the all important PATH) and functions. Those only inherit down into subshells (if exported) and anything set in the subshell does not affect the parent.

**Pull request merged**
