### PR TITLE
collation

### PR DESCRIPTION
**Pull request by reedstrm**
Ready for review and merge. This is everything for collation except some functionality needed to support index creation, i.e. group-by and link()

### CODE REVIEW

**Comment by reedstrm** [comment]
This is a WIP, comments on overall structure, please. Plan to squash  a lot of the step-by-step for the actual PR.

**Comment by pumazi** [comment]
I see you intentionally left out something to see if anyone was paying attention. :wink: 

```diff
diff --git a/setup.py b/setup.py
index 2120016..bcd0183 100644
--- a/setup.py
+++ b/setup.py
@@ -9,6 +9,7 @@ See LICENSE.txt for details.
 from setuptools import setup, find_packages
 
 install_requires = (
+    'cssselect',
     'cssselect2',
     'tinycss2',
     'lxml',```

**Comment by reedstrm** [comment]
Ah, yep, I added that back to get the xslt translation. Using it for sort. I'll fix that up.

**Comment by reedstrm** [comment]
Yay! Green checks!

**Pull request merged**
